apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  fluentd.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
    </source>
    <match **>
      type gelf
      host "#{ENV['GELF_HOST']}"
      port "#{ENV['GELF_PORT']}"
      protocol "#{ENV['PROTOCOL']}"
      tls "#{ENV['TLS']}"
      tls_options <{} (default)> for options see https://github.com/graylog-labs/gelf-rb/blob/72916932b789f7a6768c3cdd6ab69a3c942dbcef/lib/gelf/transport/tcp_tls.rb#L7-L12
      [ fluent buffered output plugin configuration ]
    </match>


