apiVersion: network.k8s.io/v1beta1
kind: Ingress
metadata:
  name: Ingress
  annotations:
    kubernetes.io./nginx.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: client-cluster-ip-service
          servicePort: 80