kind: Service
apiVersion: v1
metadata:
  name:  log-client-cluster-ip-service
spec:
  selector:
    app:  log-client
  type:  ClusterIP
  ports:
  - name:  log-client
    port:  80
    targetPort:  8080