kind: Service
apiVersion: v1
metadata:
  name:  log-service-cluster-ip-service
  namespace: fluentd-to-seq
spec:
  selector:
    app:  log-service
  type:  ClusterIP
  ports:
  - name:  log-service
    port:  8080
    targetPort:  8080