name: Docker Publish

on:
  push:
    branches: 
      - 'release/services/*'
  
defaults:
  run:
    shell: 'bash'
    working-directory: 'services/golang'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish Docker Image
      env:
        Password: ${{ secrets.DOCKER_PASSWORD }}
        Username: 'joeamedeo'
      run: ./scripts/buildAndPublish.sh
      


